### ISSUE TITLE
How to use/why DirectFB/Wayland/FB/X11 on i.MX6

### ISSUE THREAD

**Issue by angolini** [Freescale/Documentation#13]
Add a section in User Guide talking about How to use/why DirectFB/Wayland/FB/X11 on i.MX6

**Comment by Malek44** [comment]
Any news about this?
In fact this would be very helpful. I am currently looking for references on internet about FB off-screen rendering, unfortunately I can't find much.

**Comment by angolini** [comment]
Hi @Malek44,

In fact, we don't have a User Guide yet. There is a draft file, and there is the Freescale documentation, but that's all.

Are you subscribed to meta-freescale mailing list? People discuss a lot over there regarding wayland/gpu
