### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by interfaith** [Freescale/Documentation#22]
some python modules needed ?

/Documentation/user-guide$ make latexpdf
sphinx-build -b latex -d build/doctrees   source build/latex
Error: The babel.messages.pofile module cannot be found. Did you install Sphinx and its dependencies correctly?
Makefile:106: recipe for target 'latexpdf' failed
make: *** [latexpdf] Error 1

**Comment by angolini** [comment]
Let me test it over here

**Comment by otavio** [comment]
@ldnunes please take a look at this issue; @angolini reproduced the issue and seems we are lacking a dependency or so.

@angolini which OS did you use to reproduce it?

**Comment by angolini** [comment]
@otavio Ubuntu 15.10

```
~/Documentation/release-notes$ sphinx-build 
Error: The babel.messages.pofile module cannot be found. Did you install Sphinx and its dependencies correctly?
```

**Comment by ldnunes** [comment]
@interfaith, @angolini, I tried installing with the README instructions on Ubuntu 15.10 in a virtual machine and it indeed failed. But I managed to make it work by installing the following libraries and Python packages:

```shell
sudo apt-get install libfreetype6-dev libjpeg8-dev python-dev python-pip python-sphinx texlive-fonts-recommended texlive-latex-extra zlib1g-dev
sudo pip install reportlab sphinxcontrib-blockdiag
```

@otavio, @angolini I've sent a patch to the meta-freescale list updating the README instructions.

**Comment by ldnunes** [comment]
@interfaith, I'll close the issue. If you are still having problems after trying those commands feel free to re-open it.
