### ISSUE TITLE
Generate Supported Machine Tables From Single Source

### ISSUE THREAD

**Issue by TafThorne** [Freescale/Documentation#28]
Presently the Release Notes and User Guide both contain a supported machine table based on a separate source file in their own source directories. It would be simpler to maintain things going forward if a single source file was used to generate the tables in both documents.  

Over time the User Guide's table became more and more out of date compared to the Release Notes copy.  Under Pull Request #27 I updated the User Guide source file by replacing it with the Release Notes version.  Future maintenance could be simplified by either sourcing the same file directly or getting make to grab a copy.

**Comment by TafThorne** [comment]
Should this issue have been closed?  The two machine-list.inc files are still separate which I assume means the Release Notes and User Guide continue to diverge.

**Comment by angolini** [comment]
I saw your patch and I want to hand it today.

Thanks for your update! I've been closing a lot of PRs and issues which last update was <=2017. I hope the close notification can alert the author that the PR or issue is outdated and if this is still relevant, it can be reopened.

Just like this one :heart:

Thanks a lot again

**Comment by TafThorne** [comment]
It had been kicking around a while.  I had not realised it had been so
long!  Your nudge worked at least.

I added a matching GitLab pull request:
https://github.com/Freescale/Documentation/pull/29

Under that I elaborated on my slightly hacky patch:
This is perhaps not a perfect fix for #28
<https://github.com/Freescale/Documentation/issues/28> but it does make the
document sources common. I thought about moving the machine-list.inc file
out to a common directory but as the release-notes folder is where the main
focus is I felt it best to leave the source file there.

Maybe better than nothing.  Hopefully the documentation builds still work
OK for you, they did for me.

Regards, Tom

**Comment by angolini** [comment]
I've been thinking about recreate the User Guide for a while. I think at least a review is needed. But not sure how much it is relevant today.

Anyway, I could build on my 16.04 Ubuntu, but not on my 18.04.

I also learned one new word today: nudge.

And thanks for duplicating it on the mailing list.

**Comment by TafThorne** [comment]
Odd as I only tried to build on 18.04 which seems to have worked.

**Comment by angolini** [comment]
I think it's a missing package. I only don't know which.

I followed the README, so I think my missing package is also missing in the README.

If you have any clue what package you have that I don't have, please let me know (:rofl:)

**Comment by TafThorne** [comment]
If you can tell me the error message I might be able to give you a nudge in
the direction of the correct package 😉
