### ISSUE TITLE
Error while running the script for dunfell [KeyError: u'imx-boot]

### ISSUE THREAD

**Issue by angolini** [Freescale/Documentation#32]
The command used  is:

`./bitbake-metadata2doc.sh /media/daiane/TRIFORCE/yocto/dunfell/ /media/daiane/TRIFORCE/yocto/gitdm/ zeus dunfell`

my branches:

meta-freescale 3fc701d11b4b096ba016110c83fe1b48c5f3a256
meta-freescale-3rdparty 086ca01665436882176426e033c49af81f15518f
Documentation 8f0aaf01aed46e5b8a7cc5cd3c3de9587837f0bb

```
Your configuration files at tmp.MKSY59L4Rd have not been touched.
Parsing recipes: 100% |#################################################################################################################################| Time: 0:00:42
Parsing of 2159 .bb files complete (0 cached, 2159 parsed). 3241 targets, 477 skipped, 0 masked, 0 errors.
Writing ../release-notes/source/linux-default.inc
Writing ../release-notes/source/fsl-community-bsp-supported-kernels.inc
Writing ../release-notes/source/fsl-community-bsp-supported-bootloaders-descr.inc
Traceback (most recent call last):
  File "./bitbake-metadata2doc.py", line 519, in <module>
    write_bootloader_default(data, out_dir)
  File "./bitbake-metadata2doc.py", line 89, in write_bootloader_default
    boards_bloaders[board] = (image_bootloader, board_data['recipes'][image_bootloader]['version'])
KeyError: u'imx-boot'
Error running bitbake-metadata2doc.py.  Aborting.
```

**Comment by Domarys** [comment]
Hi, the error was corrected by removing the IMAGE_BOOTLOADER variable which is not used anymore, just update a meta-freescale and a meta-freescale-3rdparty. The commits that apply the correction are:
in the meta-freescale b9002e4ce93915a353eb72d73d8fa3f9a8a08190
in meta-freescale-3rdparty e2d8ca60114b4e854c804f941bced514b97c16a1
